{{- $releaseName := .Release.Name -}}
{{- $namespace := .Release.Namespace -}}
{{- $chartName := .Chart.Name -}}
{{- $chartVersion := .Chart.Version -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: php-app-secret
  namespace: {{ $namespace }}
type: Opaque
data:
  ATC_USERNAME: cmFodWwK
  ATC_PASSWORD: dGVzdHBhc3MK
