apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: rahulraju/php-app:0.0.1
        imagePullPolicy: Always
        resources: {}
        envFrom:
          - secretRef:
              name: php-app-secret
